import { Container } from "./components/Container";
import "./globals.css";
import type { Metadata } from "next";
import { ToasterProvider } from "./providers/ToasterProvider";
import { Navbar } from "./components/Navbar";
import { ClientOnly } from "./ClientOnly";
import getCurrentUser from "./actions/getCurrentUser";
import getinvitationList from "./actions/getInvitationList";
import { Hahmlet } from "next/font/google";

import dynamic from "next/dynamic";

const NewScheduleModal = dynamic(
    () => import("./components/modals/NewScheduleModal"),
);
const EditScheduleModal = dynamic(
    () => import("./components/modals/EditScheduleModal"),
);
const InviteModal = dynamic(() => import("./components/modals/InviteModal"));
const DeleteScheduleModal = dynamic(
    () => import("./components/modals/DeleteScheduleModal"),
);
const InvitationModal = dynamic(
    () => import("./components/modals/InvitationModal"),
);

export const metadata: Metadata = {
    title: "KoreanTime",
    description: "Generated by create next app",
};

const font = Hahmlet({
    weight: ["500"],
    subsets: ["latin"],
});

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const currentUser = await getCurrentUser();
    const invitationList = await getinvitationList();

    return (
        <html lang="en">
            <head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />

                <link rel="manifest" href="manifest.json" />
                <link
                    rel="apple-touch-icon"
                    href="../public/icon-192x192.png"
                ></link>
                <meta name="theme-color" content="#84A59D" />
            </head>
            <body className={font.className}>
                <ClientOnly>
                    <ToasterProvider />
                    <Navbar currentUser={currentUser} />
                    <NewScheduleModal currentUser={currentUser} />
                    <EditScheduleModal currentUser={currentUser} />
                    <InviteModal />
                    <DeleteScheduleModal />
                    <InvitationModal invitationList={invitationList} />
                </ClientOnly>
                <Container>{children}</Container>
            </body>
        </html>
    );
}
