import { Container } from "./components/Container";
import "./globals.css";
import type { Metadata } from "next";
import { ToasterProvider } from "./providers/ToasterProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ToasterProvider />
                <Container>{children}</Container>
            </body>
        </html>
    );
}
